{
 "title": "Hostname - BIND",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BIND Start Time",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "hostname.bind_info.boot-time" }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(#A, #C)",
     "targetFull": "divideSeries(hostname.dns_cachestats.QueryHits, sumSeries(hostname.dns_cachestats.QueryHits, hostname.dns_cachestats.QueryMisses))"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_cachestats.QueryHits), 2)"
    },
    {
     "target": "aliasByNode(perSecond(hostname.dns_cachestats.QueryMisses), 2)"
    }
   ]
  },
  {
   "title": "BIND Config Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "hostname.bind_info.config-time" }
   ]
  },
  {
   "title": "opcodes_in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Ops/sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_opcode_in.*), 2)"
    }
   ]
  },
  {
   "title": "qtypes_in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Queries/sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_qtypes_in.*), 2)"
    }
   ]
  },
  {
   "title": "resolver_stats_qtype",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Queries/sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_resolver_stats_qtype.*), 2)"
    }
   ]
  },
  {
   "title": "resolver_stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_resolver_stats_defview.*), 2)"
    }
   ]
  },
  {
   "title": "zone_maint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Ops/sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_zone_stats.*), 2)"
    }
   ]
  },
  {
   "title": "server_stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Ops/sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_server_stats.*), 2)"
    }
   ]
  },
  {
   "title": "QueryStats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_server_stats.Qry*), 2)"
    }
   ]
  },
  {
   "title": "Validation Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.dns_resolver_stats_defview.Val*), 2)"
    }
   ]
  },
  {
   "title": "Serial Increments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(hostname.bind_zones.*), 2)"
    }
   ]
  },
  {
   "title": "memory_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hostname.dns_memory_usage.*, 2)"
    }
   ]
  },
  {
   "title": "Zones List",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "target": "aliasByNode(hostname.bind_zones.*, 2)"
    }
   ]
  }
 ]
}